FROM node:14.5.0

WORKDIR /usr/app

COPY ./app/tsconfig.json .
COPY ./app/package.json .
COPY ./app/package-lock.json .

# RUN npm ci --production
RUN npm i
RUN npm i -g nodemon
RUN npm i -g typescript

COPY ./app/app.ts .
COPY ./app/bin ./bin
COPY ./app/src ./src
COPY ./app/.eslintrc.js .
COPY ./app/jest.config.ts .
COPY ./app/.babelrc .

RUN tsc

CMD ["npm", "start"]