FROM node:14.5.0

WORKDIR /usr/server

COPY ./app/tsconfig.json .
COPY ./app/package.json .
COPY ./app/package-lock.json .

RUN npm ci --production
RUN npm i -g nodemon
RUN npm i -g typescript

COPY ./app/app.ts .
COPY ./app/src ./src
COPY ./app/.eslintrc.js .
COPY ./app/jest.config.ts .

RUN tsc

CMD ["npm", "start"]